Repository nextcloud/user_usage_report, pull requests merged in 2022-08, with the labels that each got.

#92 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#95 [master] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#94 [stable24] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#99 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#100 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#102 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#103 [stable24] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#104 increase thumbnail cutof size to 256
  lib/AppInfo/Application.php
Labels: 3. to review
