Repository nextcloud/user_usage_report, pull requests merged in 2022-10, with the labels that each got.

#115 [stable25] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#121 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#120 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#124 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#123 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#125 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: dependencies

#128 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#127 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#126 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#130 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#129 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#131 🆕 Support Nextcloud 25 with multi-branch support
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  CHANGELOG.md
  appinfo/info.xml
  composer.json
  composer.lock
  lib/Command/Generate.php
  lib/Formatter.php
  lib/Reports/AllUsers.php
  lib/Reports/SingleUser.php
Labels: bug, enhancement

#133 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
