Repository nextcloud/user_usage_report, pull requests merged in 2024-06, with the labels that each got.

#265 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#266 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#264 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#263 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#268 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#270 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#269 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#267 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#271 ci: automate ocp updates
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: backport-request

#275 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#276 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#280 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#282 fix: handle missing display name for single user reports
  lib/Reports/SingleUser.php
Labels: 3. to review, bug

#281 fix: ensure the userid exist before adding data to report
  lib/Reports/AllUsers.php
Labels: 3. to review, bug

#287 [stable29] 1.13.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#288 [stable28] 1.12.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#289 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#290 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
