Repository nextcloud/user_usage_report, pull requests merged in 2024-09, with the labels that each got.

#310 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#311 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#312 chore(CI): Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#315 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#313 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#316 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#314 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#319 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#320 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#321 chore: update changelog
  CHANGELOG.md
Labels: 3. to review, backport-request

#324 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#326 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#325 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#327 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#328 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#329 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
